/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_lpi2c_cmsis.h"
#include "fsl_lpuart_cmsis.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA0_DMAMUX_BASEADDR DMAMUX
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN DMA0_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 15
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER DMA0_IRQHandler
/* LPI2C1 defines */
/* Definition of peripheral driver */
#define LPI2C1_CMSIS_DRIVER Driver_I2C1
/* Definition of the clock source frequency */
#define LPI2C1_CLOCK_SOURCE_FREQ 60000000UL
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL Driver_USART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE_FREQ 80000000UL
/* Debug console is initialized in the peripheral tool */
#define BOARD_INIT_DEBUG_CONSOLE_PERIPHERAL 

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA0_config;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Signal event function for component LPI2C1*/
extern void i2c_sync_event_callback(uint32_t event);
/* Get clock source frequency function for component LPI2C1 */
uint32_t LPI2C1_GetFreq(void);
/* Signal event function for component LPUART1*/
extern void ibus_uart_callback(uint32_t event);
/* Get clock source frequency function for component LPUART1 */
uint32_t LPUART1_GetFreq(void);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
