/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 16.3.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: cb07c6c3-f678-4ac9-83df-c43998cee013
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - commonSetting:
    - USART_RX_BUFFER_LEN: '32'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'edma_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - common_settings:
      - enableMinorLoopMapping: 'true'
      - enableContinuousLinkMode: 'false'
      - enableHaltOnError: 'true'
      - ERCA: 'fixedPriority'
      - enableDebugMode: 'false'
    - dma_table:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
    - edma_channels: []
    - errInterruptConfig:
      - enableErrInterrupt: 'false'
      - errorInterrupt:
        - IRQn: 'DMA_ERROR_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const edma_config_t DMA0_config = {
  .enableContinuousLinkMode = false,
  .enableHaltOnError = true,
  .enableRoundRobinArbitration = false,
  .enableDebugMode = false
};

static void DMA0_init(void) {
  /* DMA0 minor loop mapping */
  EDMA_EnableMinorLoopMapping(DMA0_DMA_BASEADDR, true);
}

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
    - interrupts:
      - 0:
        - channelId: 'int_0'
        - interrupt_t:
          - IRQn: 'DMA0_IRQn'
          - enable_interrrupt: 'noInit'
          - enable_priority: 'true'
          - priority: '15'
          - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LPI2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C1'
- type: 'lpi2c_cmsis'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpi2c_cmsis_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - fsl_i2c_cmsis:
    - mode: 'kMaster'
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - ARM_I2C_BUS_SPEED: 'ARM_I2C_BUS_SPEED_FAST'
    - signalEventFunctionId: 'i2c_sync_event_callback'
    - enableGetFreqFnCustomName: 'false'
    - getFreqFunctionCustomID: 'LPI2C1_GetFreq'
    - enableInitPinsFnCustomName: 'false'
    - initPinFunctionCustomID: 'LPI2C1_InitPins'
    - enableDeinitPinsFnCustomName: 'false'
    - deinitPinFunctionCustomID: 'LPI2C1_DeinitPins'
    - edma_channel:
      - uid: '1752722497472'
      - eDMAn: '0'
      - eDMA_source: 'kDmaRequestMuxLPI2C1'
    - edma_channel_tx:
      - uid: '1752722497479'
      - eDMAn: '1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get clock source frequency */
uint32_t LPI2C1_GetFreq(void){
  return LPI2C1_CLOCK_SOURCE_FREQ;
};

static void LPI2C1_init(void) {
  /* Initialization function */
  LPI2C1_CMSIS_DRIVER.Initialize(i2c_sync_event_callback);
  /* Power control function */
  LPI2C1_CMSIS_DRIVER.PowerControl(ARM_POWER_FULL);
  /* Configuration of the I2C communication speed */
  LPI2C1_CMSIS_DRIVER.Control(ARM_I2C_BUS_SPEED, ARM_I2C_BUS_SPEED_FAST);
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart_cmsis'
- mode: 'edma'
- custom_name_enabled: 'false'
- type_id: 'lpuart_cmsis_2.4.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - general:
    - main_config:
      - operationMode: 'ARM_USART_MODE_ASYNCHRONOUS'
      - clockSource: 'LpuartClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - power_state: 'ARM_POWER_FULL'
      - baudRate_Bps: '115200'
      - dataBits: 'ARM_USART_DATA_BITS_8'
      - parityBit: 'ARM_USART_PARITY_NONE'
      - stopBit: 'ARM_USART_STOP_BITS_1'
      - enableRX: 'false'
      - enableRXBuffer: 'true'
      - enableTX: 'false'
      - signalEventFunctionId: 'ibus_uart_callback'
      - enableGetFreqFnCustomName: 'false'
      - getFreqFunctionCustomID: 'LPUART1_GetFreq'
      - enableInitPinsFnCustomName: 'false'
      - initPinFunctionCustomID: 'LPUART1_InitPins'
      - enableDeinitPinsFnCustomName: 'false'
      - deinitPinFunctionCustomID: 'LPUART1_DeinitPins'
  - fsl_cmsis_uart:
    - edma_channels:
      - edma_rx_channel:
        - uid: '1752722497548'
        - eDMAn: '2'
        - eDMA_source: 'kDmaRequestMuxLPUART1Rx'
      - edma_tx_channel:
        - uid: '1752722497552'
        - eDMAn: '3'
        - eDMA_source: 'kDmaRequestMuxLPUART1Tx'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get clock source frequency */
uint32_t LPUART1_GetFreq(void){
  return LPUART1_CLOCK_SOURCE_FREQ;
};

static void LPUART1_init(void) {
  /* Initialize CMSIS USART */
  LPUART1_PERIPHERAL.Initialize(ibus_uart_callback);
  /* Power control of CMSIS USART */
  LPUART1_PERIPHERAL.PowerControl(ARM_POWER_FULL);
  /* Control of CMSIS USART */
  LPUART1_PERIPHERAL.Control(ARM_USART_MODE_ASYNCHRONOUS | ARM_USART_DATA_BITS_8 | ARM_USART_PARITY_NONE | ARM_USART_STOP_BITS_1, 115200);
  /* Enable or disable receiver. */
  LPUART1_PERIPHERAL.Control(ARM_USART_CONTROL_RX , 0);
  /* Enable or disable transmitter. */
  LPUART1_PERIPHERAL.Control(ARM_USART_CONTROL_TX , 0);
}

/***********************************************************************************************************************
 * PWM1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PWM1'
- type: 'pwm'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'pwm_2.6.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PWM1'
- config_sets:
  - fsl_pwm:
    - clockSource: 'SystemClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - submodules:
      - 0:
        - sm: 'kPWM_Module_0'
        - sm_id: 'SM0'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_64'
          - pwmFreq: '50 Hz'
          - pairOperation: 'kPWM_Independent'
          - operationMode: 'kPWM_EdgeAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadImmediate'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - outputTrigger_sel: ''
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'A'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'B'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'PWM1_0_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 1:
        - sm: 'kPWM_Module_2'
        - sm_id: 'SM2'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_64'
          - pwmFreq: '50 hz'
          - pairOperation: 'kPWM_Independent'
          - operationMode: 'kPWM_EdgeAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadImmediate'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - outputTrigger_sel: ''
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'A'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'B'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'PWM1_1_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
      - 2:
        - sm: 'kPWM_Module_3'
        - sm_id: 'SM3'
        - config:
          - clockSource: 'kPWM_BusClock'
          - prescale: 'kPWM_Prescale_Divide_64'
          - pwmFreq: '50 hz'
          - pairOperation: 'kPWM_Independent'
          - operationMode: 'kPWM_EdgeAligned'
          - initializationControl: 'kPWM_Initialize_LocalSync'
          - reloadLogic: 'kPWM_ReloadImmediate'
          - reloadSelect: 'kPWM_LocalReload'
          - reloadFrequency: 'kPWM_LoadEveryOportunity'
          - forceTrigger: 'kPWM_Force_Local'
          - enableDebugMode: 'false'
          - outputTrigger_sel: ''
          - loadOK: 'false'
          - startCounter: 'false'
          - interrupt_sel: ''
          - dma_used: 'false'
          - dma:
            - pwmDMA_activate: 'false'
            - captureDMA_enable: ''
            - captureDMA_source: 'kPWM_DMARequestDisable'
            - captureDMA_watermark_control: 'kPWM_FIFOWatermarksOR'
        - channels:
          - 0:
            - channel_id: 'A'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 1:
            - channel_id: 'B'
            - functionSel: 'pwmOutput'
            - pwm:
              - dutyCyclePercent: '0'
              - level: 'kPWM_HighTrue'
              - fault_channel0:
                - dismap: ''
              - faultState: 'kPWM_PwmFaultState0'
              - pwmchannelenable: 'true'
              - deadtime_input_by_force: 'kPWM_UsePwm'
              - clockSource: 'kPWM_BusClock'
              - deadtimeValue: '0'
              - interrupt_sel: ''
          - 2:
            - channel_id: 'X'
            - functionSel: 'notUsed'
        - common_interruptEn: 'false'
        - common_interrupt:
          - IRQn: 'PWM1_2_IRQn'
          - enable_interrrupt: 'enabled'
          - enable_priority: 'false'
          - priority: '0'
          - enable_custom_name: 'false'
    - faultChannels:
      - 0:
        - commonFaultSetting:
          - clockSource: 'kPWM_BusClock'
          - faultFilterPeriod: '1'
          - faultFilterCount: '3'
          - faultGlitchStretch: 'false'
        - faults:
          - 0:
            - fault_id: 'Fault0'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 1:
            - fault_id: 'Fault1'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 2:
            - fault_id: 'Fault2'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
          - 3:
            - fault_id: 'Fault3'
            - faultClearingMode: 'kPWM_Automatic'
            - faultLevelR: 'low'
            - enableCombinationalPathR: 'filtered'
            - recoverMode: 'kPWM_NoRecovery'
            - fault_int_source: 'false'
    - fault_error_interruptEn: 'false'
    - fault_error_interrupt:
      - IRQn: 'PWM1_FAULT_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* PWM main configuration */
pwm_config_t PWM1_SM0_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_64,
  .pairOperation = kPWM_Independent,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadImmediate,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
};

pwm_signal_param_t PWM1_SM0_pwm_function_config[2]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
  {
    .pwmChannel = kPWM_PwmB,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
};

pwm_config_t PWM1_SM2_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_64,
  .pairOperation = kPWM_Independent,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadImmediate,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
};

pwm_signal_param_t PWM1_SM2_pwm_function_config[2]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
  {
    .pwmChannel = kPWM_PwmB,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
};

pwm_config_t PWM1_SM3_config = {
  .clockSource = kPWM_BusClock,
  .prescale = kPWM_Prescale_Divide_64,
  .pairOperation = kPWM_Independent,
  .initializationControl = kPWM_Initialize_LocalSync,
  .reloadLogic = kPWM_ReloadImmediate,
  .reloadSelect = kPWM_LocalReload,
  .reloadFrequency = kPWM_LoadEveryOportunity,
  .forceTrigger = kPWM_Force_Local,
  .enableDebugMode = false,
};

pwm_signal_param_t PWM1_SM3_pwm_function_config[2]= {
  {
    .pwmChannel = kPWM_PwmA,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
  {
    .pwmChannel = kPWM_PwmB,
    .dutyCyclePercent = 0U,
    .level = kPWM_HighTrue,
    .faultState = kPWM_PwmFaultState0,
    .pwmchannelenable = true,
    .deadtimeValue = 0U
  },
};

const pwm_fault_input_filter_param_t PWM1_faultInputFilter_config = {
  .faultFilterPeriod = 1U,
  .faultFilterCount = 3U,
  .faultGlitchStretch = false
};
const pwm_fault_param_t PWM1_Fault0_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM1_Fault1_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM1_Fault2_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};
const pwm_fault_param_t PWM1_Fault3_fault_config = {
  .faultClearingMode = kPWM_Automatic,
  .faultLevel = false,
  .enableCombinationalPath = true,
  .recoverMode = kPWM_NoRecovery
};

static void PWM1_init(void) {
  /* Initialize PWM submodule SM0 main configuration */
  PWM_Init(PWM1_PERIPHERAL, PWM1_SM0, &PWM1_SM0_config);
  /* Initialize PWM submodule SM2 main configuration */
  PWM_Init(PWM1_PERIPHERAL, PWM1_SM2, &PWM1_SM2_config);
  /* Initialize PWM submodule SM3 main configuration */
  PWM_Init(PWM1_PERIPHERAL, PWM1_SM3, &PWM1_SM3_config);
  /* Initialize fault input filter configuration */
  PWM_SetupFaultInputFilter(PWM1_PERIPHERAL, &PWM1_faultInputFilter_config);
  /* Initialize fault channel 0 fault Fault0 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT0, &PWM1_Fault0_fault_config);
  /* Initialize fault channel 0 fault Fault1 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT1, &PWM1_Fault1_fault_config);
  /* Initialize fault channel 0 fault Fault2 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT2, &PWM1_Fault2_fault_config);
  /* Initialize fault channel 0 fault Fault3 configuration */
  PWM_SetupFaults(PWM1_PERIPHERAL, PWM1_F0_FAULT3, &PWM1_Fault3_fault_config);
  /* Initialize deadtime logic input for the channel A */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_SM0, PWM1_SM0_A, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel B */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_SM0, PWM1_SM0_B, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel A */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_SM2, PWM1_SM2_A, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel B */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_SM2, PWM1_SM2_B, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel A */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_SM3, PWM1_SM3_A, kPWM_UsePwm);
  /* Initialize deadtime logic input for the channel B */
  PWM_SetupForceSignal(PWM1_PERIPHERAL, PWM1_SM3, PWM1_SM3_B, kPWM_UsePwm);
  /* Setup PWM output setting for submodule SM0 */
  PWM_SetupPwm(PWM1_PERIPHERAL, PWM1_SM0, PWM1_SM0_pwm_function_config, 2U, kPWM_EdgeAligned, PWM1_SM0_COUNTER_FREQ_HZ, PWM1_SM0_SM_CLK_SOURCE_FREQ_HZ);
  /* Setup PWM output setting for submodule SM2 */
  PWM_SetupPwm(PWM1_PERIPHERAL, PWM1_SM2, PWM1_SM2_pwm_function_config, 2U, kPWM_EdgeAligned, PWM1_SM2_COUNTER_FREQ_HZ, PWM1_SM2_SM_CLK_SOURCE_FREQ_HZ);
  /* Setup PWM output setting for submodule SM3 */
  PWM_SetupPwm(PWM1_PERIPHERAL, PWM1_SM3, PWM1_SM3_pwm_function_config, 2U, kPWM_EdgeAligned, PWM1_SM3_COUNTER_FREQ_HZ, PWM1_SM3_SM_CLK_SOURCE_FREQ_HZ);
}

/***********************************************************************************************************************
 * DebugConsole initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DebugConsole'
- type: 'debug_console'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'debug_console_1.0.0'
- functional_group: 'BOARD_InitPeripherals'
- config_sets:
  - fsl_debug_console:
    - config:
      - SDK_DEBUGCONSOLE: 'DEBUGCONSOLE_REDIRECT_TO_TOOLCHAIN'
      - SDK_DEBUGCONSOLE_UART: 'semihost'
      - DEBUG_CONSOLE_RX_ENABLE: 'false'
      - DEBUG_CONSOLE_PRINTF_MAX_LOG_LEN: '128'
      - DEBUG_CONSOLE_SCANF_MAX_LOG_LEN: '20'
      - DEBUG_CONSOLE_ENABLE_ECHO: 'false'
      - PRINTF_FLOAT_ENABLE: 'false'
      - SCANF_FLOAT_ENABLE: 'false'
      - PRINTF_ADVANCED_ENABLE: 'false'
      - SCANF_ADVANCED_ENABLE: 'false'
      - DEBUG_CONSOLE_TRANSFER_NON_BLOCKING: 'false'
      - DEBUG_CONSOLE_TRANSMIT_BUFFER_LEN: '512'
      - DEBUG_CONSOLE_RECEIVE_BUFFER_LEN: '1024'
      - DEBUG_CONSOLE_TX_RELIABLE_ENABLE: 'true'
      - DEBUG_CONSOLE_DISABLE_RTOS_SYNCHRONIZATION: 'false'
    - debug_console_codegenerator: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void DebugConsole_init(void) {
} */

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPostInit(void)
{
  /* Interrupt vector DMA0_IRQn priority settings in the NVIC. */
  NVIC_SetPriority(INT_0_IRQN, INT_0_IRQ_PRIORITY);
  /* Interrupt INT_0_IRQN request in the NVIC is not initialized (disabled by default). */
  /* It can be enabled later by EnableIRQ(INT_0_IRQN); function call. */
}

void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMAMUX_Init(DMA0_DMAMUX_BASEADDR);
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);

  /* Initialize components */
  DMA0_init();
  LPI2C1_init();
  LPUART1_init();
  PWM1_init();
  /* Common post-initialization */
  BOARD_InitPeripherals_CommonPostInit();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
