/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_lpi2c_cmsis.h"
#include "fsl_lpuart_cmsis.h"
#include "fsl_pwm.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA0_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA0_DMAMUX_BASEADDR DMAMUX
/* NVIC interrupt vector ID (number). */
#define INT_0_IRQN DMA0_IRQn
/* NVIC interrupt vector priority. */
#define INT_0_IRQ_PRIORITY 15
/* NVIC interrupt handler identifier. */
#define INT_0_IRQHANDLER DMA0_IRQHandler
/* LPI2C1 defines */
/* Definition of peripheral driver */
#define LPI2C1_SENSORS_CMSIS_DRIVER Driver_I2C1
/* Definition of the clock source frequency */
#define LPI2C1_SENSORS_CLOCK_SOURCE_FREQ 60000000UL
/* Definition of peripheral ID */
#define LPUART1_IBUS_PERIPHERAL Driver_USART1
/* Definition of the clock source frequency */
#define LPUART1_IBUS_CLOCK_SOURCE_FREQ 80000000UL
/* Definition of peripheral ID */
#define PWM1_PERIPHERAL PWM1
/* Definition of submodule 0 ID */
#define PWM1_SM0 kPWM_Module_0
/* Definition of clock source of submodule 0 frequency in Hertz */
#define PWM1_SM0_SM_CLK_SOURCE_FREQ_HZ 125000000U
/* Definition of submodule 0 counter clock source frequency in Hertz - PWM1_SM0_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define PWM1_SM0_COUNTER_CLK_SOURCE_FREQ_HZ 1953125U
/* Definition of submodule 0 counter (PWM) frequency in Hertz */
#define PWM1_SM0_COUNTER_FREQ_HZ 50U
/* Definition of submodule 0 channel A ID */
#define PWM1_SM0_A kPWM_PwmA
/* Definition of submodule 0 channel B ID */
#define PWM1_SM0_B kPWM_PwmB
/* Definition of submodule 0 channel X ID */
#define PWM1_SM0_X kPWM_PwmX
/* Definition of submodule 2 ID */
#define PWM1_SM2 kPWM_Module_2
/* Definition of clock source of submodule 2 frequency in Hertz */
#define PWM1_SM2_SM_CLK_SOURCE_FREQ_HZ 125000000U
/* Definition of submodule 2 counter clock source frequency in Hertz - PWM1_SM2_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define PWM1_SM2_COUNTER_CLK_SOURCE_FREQ_HZ 1953125U
/* Definition of submodule 2 counter (PWM) frequency in Hertz */
#define PWM1_SM2_COUNTER_FREQ_HZ 50U
/* Definition of submodule 2 channel A ID */
#define PWM1_SM2_A kPWM_PwmA
/* Definition of submodule 2 channel B ID */
#define PWM1_SM2_B kPWM_PwmB
/* Definition of submodule 2 channel X ID */
#define PWM1_SM2_X kPWM_PwmX
/* Definition of submodule 3 ID */
#define PWM1_SM3 kPWM_Module_3
/* Definition of clock source of submodule 3 frequency in Hertz */
#define PWM1_SM3_SM_CLK_SOURCE_FREQ_HZ 125000000U
/* Definition of submodule 3 counter clock source frequency in Hertz - PWM1_SM3_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define PWM1_SM3_COUNTER_CLK_SOURCE_FREQ_HZ 1953125U
/* Definition of submodule 3 counter (PWM) frequency in Hertz */
#define PWM1_SM3_COUNTER_FREQ_HZ 50U
/* Definition of submodule 3 channel A ID */
#define PWM1_SM3_A kPWM_PwmA
/* Definition of submodule 3 channel B ID */
#define PWM1_SM3_B kPWM_PwmB
/* Definition of submodule 3 channel X ID */
#define PWM1_SM3_X kPWM_PwmX
/* Definition of fault Fault0 ID */
#define PWM1_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define PWM1_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define PWM1_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define PWM1_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define LPUART3_GPS_PERIPHERAL Driver_USART3
/* Definition of the clock source frequency */
#define LPUART3_GPS_CLOCK_SOURCE_FREQ 80000000UL
/* Definition of peripheral ID */
#define LPUART2_TELE_PERIPHERAL Driver_USART4
/* Definition of the clock source frequency */
#define LPUART2_TELE_CLOCK_SOURCE_FREQ 80000000UL
/* Debug console is initialized in the peripheral tool */
#define BOARD_INIT_DEBUG_CONSOLE_PERIPHERAL 

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA0_config;
extern pwm_config_t PWM1_SM0_config;

extern pwm_signal_param_t PWM1_SM0_pwm_function_config[2];
extern pwm_config_t PWM1_SM2_config;

extern pwm_signal_param_t PWM1_SM2_pwm_function_config[2];
extern pwm_config_t PWM1_SM3_config;

extern pwm_signal_param_t PWM1_SM3_pwm_function_config[2];
extern const pwm_fault_input_filter_param_t PWM1_faultInputFilter_config;
extern const pwm_fault_param_t PWM1_Fault0_fault_config;
extern const pwm_fault_param_t PWM1_Fault1_fault_config;
extern const pwm_fault_param_t PWM1_Fault2_fault_config;
extern const pwm_fault_param_t PWM1_Fault3_fault_config;

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Signal event function for component LPI2C1_Sensors*/
extern void i2c_sync_event_callback(uint32_t event);
/* Get clock source frequency function for component LPI2C1_Sensors */
uint32_t LPI2C1_GetFreq(void);
/* Signal event function for component LPUART1_Ibus*/
extern void ibus_uart_callback(uint32_t event);
/* Get clock source frequency function for component LPUART1_Ibus */
uint32_t LPUART1_GetFreq(void);
/* Get clock source frequency function for component LPUART3_GPS */
uint32_t LPUART3_GetFreq(void);
/* Get clock source frequency function for component LPUART2_Tele */
uint32_t LPUART4_GetFreq(void);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
