/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK 0x18U /*!< Select GPIO1 or GPIO2: affected bits mask */

/* GPIO_03 (number 10), LED_D13 */
/* Routed pin properties */
#define BOARD_INITPINS_SAI1_RXD0_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_SAI1_RXD0_SIGNAL                               gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_SAI1_RXD0_CHANNEL                                      3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SAI1_RXD0_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SAI1_RXD0_GPIO_PIN                                     3U   /*!< GPIO pin number */
#define BOARD_INITPINS_SAI1_RXD0_GPIO_PIN_MASK                        (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SAI1_RXD0_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SAI1_RXD0_PIN                                          3U   /*!< PORT pin number */
#define BOARD_INITPINS_SAI1_RXD0_PIN_MASK                             (1U << 3U)   /*!< PORT pin mask */

/* GPIO_SD_01 (number 75), PWM0B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM0B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM0B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM0B_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_SD_02 (number 74), PWM0A */
/* Routed pin properties */
#define BOARD_INITPINS_PWM0A_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM0A_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_PWM0A_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_05 (number 8), PWM2B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM2B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM2B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM2B_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_06 (number 6), PWM2A */
/* Routed pin properties */
#define BOARD_INITPINS_PWM2A_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM2A_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_PWM2A_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_07 (number 5), PWM3B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM3B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM3B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM3B_CHANNEL                                          3U   /*!< Signal channel */

/* GPIO_08 (number 4), PWM3A */
/* Routed pin properties */
#define BOARD_INITPINS_PWM3A_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM3A_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_PWM3A_CHANNEL                                          3U   /*!< Signal channel */

/* GPIO_09 (number 3), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                      RXD   /*!< Signal name */

/* GPIO_10 (number 2), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                      TXD   /*!< Signal name */

/* GPIO_12 (number 80), UART3_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART3_TXD_PERIPHERAL                              LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_UART3_TXD_SIGNAL                                      TXD   /*!< Signal name */

/* GPIO_11 (number 1), UART3_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART3_RXD_PERIPHERAL                              LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_UART3_RXD_SIGNAL                                      RXD   /*!< Signal name */

/* GPIO_04 (number 9), MEAS_TIME */
/* Routed pin properties */
#define BOARD_INITPINS_MEAS_TIME_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MEAS_TIME_SIGNAL                               gpiomux_io   /*!< Signal name */
#define BOARD_INITPINS_MEAS_TIME_CHANNEL                                      4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MEAS_TIME_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MEAS_TIME_GPIO_PIN                                     4U   /*!< GPIO pin number */
#define BOARD_INITPINS_MEAS_TIME_GPIO_PIN_MASK                        (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MEAS_TIME_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MEAS_TIME_PIN                                          4U   /*!< PORT pin number */
#define BOARD_INITPINS_MEAS_TIME_PIN_MASK                             (1U << 4U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
