/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MIMXRT1011xxxxx
package_id: MIMXRT1011DAE5A
mcu_data: ksdk2_0
processor_version: 16.3.0
external_user_signals: {}
pin_labels:
- {pin_num: '3', pin_signal: GPIO_09, label: UART1_RXD, identifier: UART1_RXD}
- {pin_num: '2', pin_signal: GPIO_10, label: UART1_TXD, identifier: UART1_TXD}
- {pin_num: '65', pin_signal: GPIO_SD_10, label: FlexSPI_CLK, identifier: FlexSPI_CLK}
- {pin_num: '66', pin_signal: GPIO_SD_09, label: FlexSPI_D0_A, identifier: FlexSPI_D0_A}
- {pin_num: '68', pin_signal: GPIO_SD_07, label: FlexSPI_D1_A, identifier: FlexSPI_D1_A}
- {pin_num: '67', pin_signal: GPIO_SD_08, label: FlexSPI_D2_A, identifier: FlexSPI_D2_A}
- {pin_num: '64', pin_signal: GPIO_SD_11, label: SD_CD, identifier: FlexSPI_D3_A;SD_CD}
- {pin_num: '69', pin_signal: GPIO_SD_06, label: FlexSPI_SS0, identifier: FlexSPI_SS0}
- {pin_num: '10', pin_signal: GPIO_03, label: LED_D13, identifier: SAI1_RXD0}
- {pin_num: '75', pin_signal: GPIO_SD_01, label: PWM0B, identifier: PWM1;PWM1B;PWM0B}
- {pin_num: '74', pin_signal: GPIO_SD_02, label: PWM0A, identifier: PWM1;PWM1A;PWM0A}
- {pin_num: '8', pin_signal: GPIO_05, label: PWM2B, identifier: PWM2B}
- {pin_num: '6', pin_signal: GPIO_06, label: PWM2A, identifier: PWM2A}
- {pin_num: '5', pin_signal: GPIO_07, label: PWM3B, identifier: PWM3B}
- {pin_num: '4', pin_signal: GPIO_08, label: PWM3A, identifier: PWM3A}
- {pin_num: '80', pin_signal: GPIO_12, label: UART3_TXD, identifier: UART3_TXD}
- {pin_num: '1', pin_signal: GPIO_11, label: UART3_RXD, identifier: UART3_RXD}
- {pin_num: '57', pin_signal: GPIO_AD_03, label: SD_MISO, identifier: SD_MISO}
- {pin_num: '52', pin_signal: GPIO_AD_06, label: SD_CLK, identifier: SD_CLK}
- {pin_num: '56', pin_signal: GPIO_AD_04, label: SD_MOSI, identifier: SD_MOSI}
- {pin_num: '43', pin_signal: GPIO_AD_14, label: SD_CS, identifier: SD_CS}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_xbara.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '48', peripheral: ARM, signal: arm_trace_swo, pin_signal: GPIO_AD_09}
  - {pin_num: '12', peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_01, slew_rate: Fast, software_input_on: Enable, open_drain: Enable, pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '11', peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_02, slew_rate: Fast, software_input_on: Enable, open_drain: Enable, pull_up_down_config: Pull_Up_22K_Ohm}
  - {pin_num: '10', peripheral: GPIO1, signal: 'gpiomux_io, 03', pin_signal: GPIO_03, direction: OUTPUT}
  - {pin_num: '75', peripheral: PWM1, signal: 'B, 0', pin_signal: GPIO_SD_01, identifier: PWM0B, direction: OUTPUT, slew_rate: Fast, software_input_on: Enable, pull_keeper_enable: Enable}
  - {pin_num: '74', peripheral: PWM1, signal: 'A, 0', pin_signal: GPIO_SD_02, identifier: PWM0A, direction: OUTPUT, slew_rate: Fast, software_input_on: Enable, pull_keeper_enable: Enable}
  - {pin_num: '8', peripheral: PWM1, signal: 'B, 2', pin_signal: GPIO_05, direction: OUTPUT, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '6', peripheral: PWM1, signal: 'A, 2', pin_signal: GPIO_06, direction: OUTPUT, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '5', peripheral: PWM1, signal: 'B, 3', pin_signal: GPIO_07, direction: OUTPUT, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '4', peripheral: PWM1, signal: 'A, 3', pin_signal: GPIO_08, direction: OUTPUT, slew_rate: Fast, software_input_on: Enable}
  - {peripheral: PWM1, signal: 'FAULT, 0', pin_signal: LOGIC_HIGH}
  - {peripheral: PWM1, signal: 'FAULT, 1', pin_signal: LOGIC_HIGH}
  - {peripheral: PWM1, signal: 'FAULT, 2', pin_signal: LOGIC_HIGH}
  - {peripheral: PWM1, signal: 'FAULT, 3', pin_signal: LOGIC_HIGH}
  - {pin_num: '3', peripheral: LPUART1, signal: RXD, pin_signal: GPIO_09, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '2', peripheral: LPUART1, signal: TXD, pin_signal: GPIO_10, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '80', peripheral: LPUART3, signal: TXD, pin_signal: GPIO_12, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '1', peripheral: LPUART3, signal: RXD, pin_signal: GPIO_11, slew_rate: Fast, software_input_on: Enable}
  - {pin_num: '64', peripheral: GPIO2, signal: 'gpio_io, 11', pin_signal: GPIO_SD_11, identifier: SD_CD, direction: INPUT}
  - {pin_num: '57', peripheral: LPSPI1, signal: SDI, pin_signal: GPIO_AD_03}
  - {pin_num: '52', peripheral: LPSPI1, signal: SCK, pin_signal: GPIO_AD_06}
  - {pin_num: '56', peripheral: LPSPI1, signal: SDO, pin_signal: GPIO_AD_04}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           
  CLOCK_EnableClock(kCLOCK_Xbar1);            

  /* GPIO configuration of SAI1_RXD0 on GPIO_03 (pin 10) */
  gpio_pin_config_t SAI1_RXD0_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_03 (pin 10) */
  GPIO_PinInit(GPIO1, 3U, &SAI1_RXD0_config);

  /* GPIO configuration of SD_CD on GPIO_SD_11 (pin 64) */
  gpio_pin_config_t SD_CD_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_11 (pin 64) */
  GPIO_PinInit(GPIO2, 11U, &SD_CD_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_01_LPI2C1_SDA, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_02_LPI2C1_SCL, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_03_GPIOMUX_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_05_FLEXPWM1_PWM2_B, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_06_FLEXPWM1_PWM2_A, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_07_FLEXPWM1_PWM3_B, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_08_FLEXPWM1_PWM3_A, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_09_LPUART1_RXD, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_10_LPUART1_TXD, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_11_LPUART3_RXD, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_12_LPUART3_TXD, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_03_LPSPI1_SDI, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_04_LPSPI1_SDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_06_LPSPI1_SCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_09_ARM_TRACE_SWO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_01_FLEXPWM1_PWM0_B, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_02_FLEXPWM1_PWM0_A, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_11_GPIO2_IO11, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_SEL(0x00U)      
    );
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputLogicHigh, kXBARA1_OutputFlexpwm1Fault0); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputLogicHigh, kXBARA1_OutputFlexpwm1Fault1); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputLogicHigh, kXBARA1_OutputFlexpwm1Fault2); 
  XBARA_SetSignalsConnection(XBARA, kXBARA1_InputLogicHigh, kXBARA1_OutputFlexpwm1Fault3); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_01_LPI2C1_SDA, 0xD8A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_02_LPI2C1_SCL, 0xD8A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_05_FLEXPWM1_PWM2_B, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_06_FLEXPWM1_PWM2_A, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_07_FLEXPWM1_PWM3_B, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_08_FLEXPWM1_PWM3_A, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_09_LPUART1_RXD, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_10_LPUART1_TXD, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_11_LPUART3_RXD, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_12_LPUART3_TXD, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_01_FLEXPWM1_PWM0_B, 0x10A1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_02_FLEXPWM1_PWM0_A, 0x10A1U); 
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
