/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2018-2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __RTE_DEVICE_H
#define __RTE_DEVICE_H

/***********************************************************************************************************************
 * Driver name mapping
 **********************************************************************************************************************/
/* Enable peripheral */
#define RTE_I2C1 1
/* Enable I2C DMA */
#define RTE_I2C1_DMA_EN 1
/* Enable peripheral */
#define RTE_USART1 1
/* Enable USART DMA */
#define RTE_USART1_DMA_EN 1
/* Enable peripheral */
#define RTE_USART3 1
/* Enable USART DMA */
#define RTE_USART3_DMA_EN 1
/* Enable peripheral */
#define RTE_SPI1 1
/* Enable SPI DMA */
#define RTE_SPI1_DMA_EN 1

/***********************************************************************************************************************
 * Driver configuration
 **********************************************************************************************************************/
/* I2C1 configuration */
/* Used DMA device */
#define RTE_I2C1_DMA_RX_DMA_BASE DMA0
/* Selected Rx DMA channel number */
#define RTE_I2C1_DMA_RX_CH 0
/* DMAMUX device that is used for muxing of the Rx request */
#define RTE_I2C1_DMA_RX_DMAMUX_BASE DMAMUX
/* Rx DMA source request */
#define RTE_I2C1_DMA_RX_PERI_SEL (uint16_t) kDmaRequestMuxLPI2C1
/* Used DMA device */
#define RTE_I2C1_DMA_TX_DMA_BASE DMA0
/* Selected Tx DMA channel number */
#define RTE_I2C1_DMA_TX_CH 1
/* DMAMUX device that is used for muxing of the Tx request */
#define RTE_I2C1_DMA_TX_DMAMUX_BASE DMAMUX
/* Tx DMA source request */
#define RTE_I2C1_DMA_TX_PERI_SEL (uint16_t) kDmaRequestMuxLPI2C1
/* All USART Rx buffers length */
#define USART_RX_BUFFER_LEN 32
/* Enable RX buffer */
#define USART1_RX_BUFFER_ENABLE 1
/* Selected DMA channel number. */
#define RTE_USART1_DMA_RX_CH 3
/* LPUART1_Ibus DMA source request. */
#define RTE_USART1_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART1Rx
/* DMAMUX device that is used for muxing of the request. */
#define RTE_USART1_DMA_RX_DMAMUX_BASE DMAMUX
/* Used DMA device. */
#define RTE_USART1_DMA_RX_DMA_BASE DMA0
/* Selected DMA channel number. */
#define RTE_USART1_DMA_TX_CH 2
/* LPUART1_Ibus DMA source request. */
#define RTE_USART1_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART1Tx
/* DMAMUX device that is used for muxing of the request. */
#define RTE_USART1_DMA_TX_DMAMUX_BASE DMAMUX
/* Used DMA device. */
#define RTE_USART1_DMA_TX_DMA_BASE DMA0
/* Enable RX buffer */
#define USART3_RX_BUFFER_ENABLE 1
/* Selected DMA channel number. */
#define RTE_USART3_DMA_RX_CH 5
/* LPUART3_GPS DMA source request. */
#define RTE_USART3_DMA_RX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART3Rx
/* DMAMUX device that is used for muxing of the request. */
#define RTE_USART3_DMA_RX_DMAMUX_BASE DMAMUX
/* Used DMA device. */
#define RTE_USART3_DMA_RX_DMA_BASE DMA0
/* Selected DMA channel number. */
#define RTE_USART3_DMA_TX_CH 4
/* LPUART3_GPS DMA source request. */
#define RTE_USART3_DMA_TX_PERI_SEL (uint8_t) kDmaRequestMuxLPUART3Tx
/* DMAMUX device that is used for muxing of the request. */
#define RTE_USART3_DMA_TX_DMAMUX_BASE DMAMUX
/* Used DMA device. */
#define RTE_USART3_DMA_TX_DMA_BASE DMA0
/* PCS to SCK delay. */
#define RTE_SPI1_PCS_TO_SCK_DELAY 0
/* SCK to PCS delay. */
#define RTE_SPI1_SCK_TO_PSC_DELAY 0
/* Between transfer delay. */
#define RTE_SPI1_BETWEEN_TRANSFER_DELAY 0
/* Peripheral chip select. */
#define RTE_SPI1_MASTER_PCS_PIN_SEL kLPSPI_MasterPcs0
/* Selected DMA channel number. */
#define RTE_SPI1_DMA_RX_CH 6
/* LPSPI1_SD DMA source request. */
#define RTE_SPI1_DMA_RX_PERI_SEL (uint16_t) kDmaRequestMuxLPSPI1Rx
/* DMAMUX device that is used for muxing of the request. */
#define RTE_SPI1_DMA_RX_DMAMUX_BASE DMAMUX
/* Used DMA device. */
#define RTE_SPI1_DMA_RX_DMA_BASE DMA0
/* Selected DMA channel number. */
#define RTE_SPI1_DMA_TX_CH 7
/* LPSPI1_SD DMA source request. */
#define RTE_SPI1_DMA_TX_PERI_SEL (uint16_t) kDmaRequestMuxLPSPI1Tx
/* DMAMUX device that is used for muxing of the request. */
#define RTE_SPI1_DMA_TX_DMAMUX_BASE DMAMUX
/* Used DMA device. */
#define RTE_SPI1_DMA_TX_DMA_BASE DMA0


#endif /* __RTE_DEVICE_H */
