/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_02 (number 74), PWM0A */
/* Routed pin properties */
#define BOARD_INITPINS_PWM0A_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM0A_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_PWM0A_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_05 (number 8), PWM2B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM2B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM2B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM2B_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_06 (number 6), PWM2A */
/* Routed pin properties */
#define BOARD_INITPINS_PWM2A_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM2A_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_PWM2A_CHANNEL                                          2U   /*!< Signal channel */

/* GPIO_07 (number 5), PWM3B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM3B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM3B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM3B_CHANNEL                                          3U   /*!< Signal channel */

/* GPIO_08 (number 4), PWM3A */
/* Routed pin properties */
#define BOARD_INITPINS_PWM3A_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM3A_SIGNAL                                            A   /*!< Signal name */
#define BOARD_INITPINS_PWM3A_CHANNEL                                          3U   /*!< Signal channel */

/* GPIO_12 (number 80), UART3_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART3_TXD_PERIPHERAL                              LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_UART3_TXD_SIGNAL                                      TXD   /*!< Signal name */

/* GPIO_11 (number 1), UART3_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART3_RXD_PERIPHERAL                              LPUART3   /*!< Peripheral name */
#define BOARD_INITPINS_UART3_RXD_SIGNAL                                      RXD   /*!< Signal name */

/* GPIO_SD_01 (number 75), PWM0B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM0B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM0B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM0B_CHANNEL                                          0U   /*!< Signal channel */

/* GPIO_10 (number 2), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                      TXD   /*!< Signal name */

/* GPIO_09 (number 3), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                      RXD   /*!< Signal name */

/* GPIO_04 (number 9), PWM1A */
/* Routed pin properties */
#define BOARD_INITPINS_MEAS_TIME_PERIPHERAL                                 PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_MEAS_TIME_SIGNAL                                        A   /*!< Signal name */
#define BOARD_INITPINS_MEAS_TIME_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_03 (number 10), PWM1B */
/* Routed pin properties */
#define BOARD_INITPINS_PWM1B_PERIPHERAL                                     PWM1   /*!< Peripheral name */
#define BOARD_INITPINS_PWM1B_SIGNAL                                            B   /*!< Signal name */
#define BOARD_INITPINS_PWM1B_CHANNEL                                          1U   /*!< Signal channel */

/* GPIO_SD_10 (number 65), FlexSPI_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_CLK_PERIPHERAL                            FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_CLK_SIGNAL                         FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_09 (number 66), FlexSPI_D0_A */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D0_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D0_A_SIGNAL                       FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_08 (number 67), FlexSPI_D2_A */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D2_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D2_A_SIGNAL                       FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_07 (number 68), FlexSPI_D1_A */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_D1_A_PERIPHERAL                           FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_D1_A_SIGNAL                       FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_06 (number 69), FlexSPI_SS0 */
/* Routed pin properties */
#define BOARD_INITPINS_FlexSPI_SS0_PERIPHERAL                            FLEXSPI   /*!< Peripheral name */
#define BOARD_INITPINS_FlexSPI_SS0_SIGNAL                        FLEXSPI_A_SS0_B   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
